# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order_app/grpc_contracts/inventory.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'order_app/grpc_contracts/inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(order_app/grpc_contracts/inventory.proto\x12\x18order_app.grpc_contracts\"/\n\x0eReserveRequest\x12\x0b\n\x03sku\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"3\n\x0fReserveResponse\x12\x10\n\x08reserved\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t2r\n\x10InventoryService\x12^\n\x07Reserve\x12(.order_app.grpc_contracts.ReserveRequest\x1a).order_app.grpc_contracts.ReserveResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_app.grpc_contracts.inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESERVEREQUEST']._serialized_start=70
  _globals['_RESERVEREQUEST']._serialized_end=117
  _globals['_RESERVERESPONSE']._serialized_start=119
  _globals['_RESERVERESPONSE']._serialized_end=170
  _globals['_INVENTORYSERVICE']._serialized_start=172
  _globals['_INVENTORYSERVICE']._serialized_end=286
# @@protoc_insertion_point(module_scope)
